import time
import speech_recognition as sr
import pyautogui
from pynput.keyboard import Key, Controller as KeyboardController, KeyCode
from pynput.mouse import Button, Controller as MouseController
import ctypes
from ctypes import wintypes
from playsound import playsound


def main():
    keyboard = KeyboardController()
    mouse = MouseController()
    class MyServer():
        def do_GET():
            if __name__ == "__main__":        

                with sr.Microphone() as source:
                    r = sr.Recognizer()
                    print("Listening")
                    audio_text = r.listen(source)
                    
                    try:
                    # using google speech recognition
                        text = r.recognize_google(audio_text)
                        print("Text: "+ text)
                        
                        #if I say "shit" or "die", spam run, teabag, run, teabag
                        if "die" in text:
                            print('Paula Deen: get buttered and get fuckt')
                            playsound('C:/Users/morge/Desktop/Twitch_Plays_Bot/assets/hahayousaiddie.mp3')
                            keyboard.press('w')
                            time.sleep(6)
                            keyboard.release('w')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('w')
                            time.sleep(6)
                            keyboard.release('w')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            print('Paula Deen: idiot')

                        if "s***" in text:
                            print('Paula Deen: get buttered and get fuckt')
                            playsound('C:/Users/morge/Desktop/Twitch_Plays_Bot/assets/hahayousaidshit.mp3')
                            keyboard.press('w')
                            time.sleep(6)
                            keyboard.release('w')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('w')
                            time.sleep(6)
                            keyboard.release('w')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            time.sleep(.2)
                            keyboard.press('c')
                            time.sleep(.2)
                            keyboard.release('c')
                            print('Paula Deen: idiot')

                        #if I say "stop" or "hi", systematically select
                        #everything in my hotbar and throw it on the ground
                        if "stop" in text:
                            print ("Paula Deen: goodbye bitch")
                            playsound('C:/Users/morge/Desktop/Twitch_Plays_Bot/assets/yousaidstopdummy.mp3')
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            print ('Paula Deen: I hate you')

                        if "hi" in text or "high" in text:
                            print ("Paula Deen: goodbye bitch")
                            playsound('C:/Users/morge/Desktop/Twitch_Plays_Bot/assets/yousaidhidummy.mp3')
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            mouse.scroll(0,1)
                            time.sleep(.5)
                            keyboard.press('g')
                            time.sleep(.5)
                            keyboard.release('g')
                            time.sleep(.5)
                            print ('Paula Deen: I hate you')

                        #if I say "sucks" or "chat", spam a thousand jumps#
                        if "sucks" in text:
                            print('Paula Deen: no u')
                            playsound('C:/Users/morge/Desktop/Twitch_Plays_Bot/assets/yousuckimeanyousaidsucks.mp3')
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            print('Paula Deen: bless your very heart and soul')

                        if "chat" in text:
                            print('Paula Deen: no u')
                            playsound('C:/Users/morge/Desktop/Twitch_Plays_Bot/assets/yousaidchatagain.mp3')
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            time.sleep(.5)
                            keyboard.press(Key.space)
                            time.sleep(.5)
                            keyboard.release(Key.space)
                            print('Paula Deen: bless your very heart and soul')
                        main()
                    except:
                        print("Sorry, I did not get that")
                        main()

    MyServer.do_GET()
    
if __name__ == '__main__':
    main()